name: admin-ui-ivr
namespace: official
version: 1.1.1-2
author: Wazo Team
display_name: IVR
min_wazo_version: 18.01
tags:
  - beta
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-ivr
