name: admin-ui-ivr
namespace: official
version: 1.2.0-3
author: Wazo Team
display_name: IVR
min_wazo_version: 18.02
tags:
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-ivr
depends:
  - name: admin-ui-sound
    namespace: official
