name: admin-ui-ivr
namespace: official
version: 0.0.3
author: Wazo Team
display_name: IVR
min_wazo_version: 17.16
tags:
  - beta
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-ivr
